name: automerge
on:
  pull_request:
    types:
      - labeled
    branches:
      - master

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"